export const SEARCH_MOVIE = 'SEARCH_MOVIE'
export const FETCH_MOVIES = 'FETCH_MOVIES'


// FETCH UPCOMING MOVIE
export const FETCH_UPCOMING_REQUEST = 'FETCH_UPCOMING_MOVIE'
export const FETCH_UPCOMING_SUCCESS = 'FETCH_UPCOMING_SUCCESS'
export const FETCH_UPCOMING_FAILURE = 'FETCH_UPCOMING_FAILURE'
// FETCH POPULAR MOVIE
export const FETCH_POPULAR_REQUEST = 'FETCH_POPULAR_REQUEST'
export const FETCH_POPULAR_SUCCESS = 'FETCH_POPULAR_SUCCESS'
export const FETCH_POPULAR_FAILURE = 'FETCH_POPULAR_FAILURE'

// FETCH TOPRATED MOVIE
export const FETCH_TOPRATED_REQUEST = 'FETCH_TOPRATED_REQUEST'
export const FETCH_TOPRATED_SUCCESS = 'FETCH_TOPRATED_SUCCESS'
export const FETCH_TOPRATED_FAILURE = 'FETCH_TOPRATED_FAILURE'

// FETCH
export const FETCH_NOWPLAYING_MOVIE = 'FETCH_NOWPLAYING_MOVIE'